version: '3'
services:
  app:
    build: .
    command: tensorboard --logdir data
    tty: true
    ports:
      - 6066:6006
    volumes:
      - .:/app
    working_dir: /app
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
